### ISSUE TITLE
.mobi no longer supported by kindle

### ISSUE THREAD

**Issue by niky45** [JCalebBR/LectitioLexicanus#2]
at least on my kindle 2019 I can't directly send a .mobi book (of any kind) through the send to kindle page or email address. 

project should get updated to use .epub

**Comment by JCalebBR** [comment]
You can try connecting the kindle to a PC and sending files that way, it should still work as I have the same model as you

**Comment by niky45** [comment]
I mean, I converted it to azw3 and did that, and it worked... (converting to epub and doing send to kindle didn't seem to work for some reason)

problem is, it's not in my library so it won't sync to other devices

**Comment by JCalebBR** [comment]
Yeah that's as expected, it's a local file, it isn't registered anywhere online. This is similar to when you use calibre to load books directly instead of downloading via the store.
Will close issue since it looks like i's been resolved

**Comment by JCalebBR** [comment]
Yeah that's as expected, it's a local file, it isn't registered anywhere online. This is similar to when you use calibre to load books directly instead of downloading via the store.
Will close issue since it looks like i's been resolved
